<!--====== jquery js ======-->
<script src={{ asset("assets/js/jquery.min.js") }}></script>
<!--====== Bootstrap js ======-->
<script src={{ asset("assets/js/bootstrap.min.js") }}></script>
<!--====== Inview js ======-->
<script src={{ asset("assets/js/jquery.inview.min.js") }}></script>
<!--====== Slick js ======-->
<script src={{ asset("assets/js/slick.min.js") }}></script>
<!--====== Lity js ======-->
<script src={{ asset("assets/js/lity.min.js") }}></script>
<!--====== Wow js ======-->
<script src={{ asset("assets/js/wow.min.js") }}></script>
<!--====== Main js ======-->
<script src={{ asset("assets/js/main.js") }}></script>